import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.95.0/+esm";
const SUPABASE_URL="https://kjlocnicimhgjfhznvmn.supabase.co";
const SUPABASE_KEY="sb_publishable_5nRdHITW2R3cZaYW_lo1Bg_H1TRhsKo";
export const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
export const $=id=>document.getElementById(id);
export const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
export const modeName=m=>({fcfs:"1 · Primero en llegar",lottery:"2 · Ventana + sorteo",rotation:"3 · Rotación justa"}[m]||m);
export const fmt=d=>new Intl.DateTimeFormat("es-EC",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Guayaquil"}).format(new Date(d));
export const fmtTime=d=>new Intl.DateTimeFormat("es-EC",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZone:"America/Guayaquil"}).format(new Date(d));
export let state=null;
export let deviceToken=localStorage.getItem("futbol_device_token")||"";
export let deviceIdentity=null;
let serverAnchor=null,localAnchor=null;
export async function api(action,payload={}){const {data,error}=await supabase.rpc("api_dispatch",{p_action:action,p_payload:payload});if(error)throw new Error(error.message);return data}
export function result(id,msg,error=false){const e=$(id);if(!e)return;e.textContent=msg;e.classList.remove("hidden","error");if(error)e.classList.add("error")}
export function currentConfirmed(){return state?.lists?.confirmed||[]}
export function syncClock(t){serverAnchor=new Date(t).getTime();localAnchor=Date.now()}
function nowServer(){return serverAnchor==null?Date.now():serverAnchor+(Date.now()-localAnchor)}
export function tick(){const n=new Date(nowServer());if($("serverClock"))$("serverClock").textContent=fmtTime(n);if($("serverDate"))$("serverDate").textContent=new Intl.DateTimeFormat("es-EC",{weekday:"long",day:"numeric",month:"long",timeZone:"America/Guayaquil"}).format(n);if(state?.match)tickCountdown()}
export function tickCountdown(){if(!state?.match)return;const m=state.match,n=nowServer(),o=new Date(m.opens_at).getTime(),c=new Date(m.closes_at).getTime();let t,l;if(n<o){t=o;l="La inscripción abre en"}else if(n<c){t=c;l="La inscripción cierra en"}else{t=null;l="Inscripción cerrada"}$("countdownLabel").textContent=l;if(!t){$("countdown").textContent="CERRADA"}else{const s=Math.max(0,Math.floor((t-n)/1000));$("countdown").textContent=String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}const open=n>=o&&n<c;if($("joinBtn"))$("joinBtn").disabled=!open;if($("joinKnownBtn"))$("joinKnownBtn").disabled=!open}
function renderList(id,items){const el=$(id);if(!el)return;el.innerHTML=items.length?items.map((x,i)=>`<li><strong>${i+1}.</strong> ${esc(x.name)}<span class="stamp">${x.registered_at?"Servidor: "+fmtTime(x.registered_at):""}${x.promoted_at?" · Ascenso: "+fmtTime(x.promoted_at):""}</span></li>`).join(""):'<li class="hint">Sin jugadores todavía</li>'}
export async function refreshIdentity(){deviceIdentity=null;if(deviceToken){const r=await api("device_identity",{device_token:deviceToken});if(r.valid)deviceIdentity=r;else{deviceToken="";localStorage.removeItem("futbol_device_token")}}renderIdentity()}
export function forgetDevice(){deviceToken="";deviceIdentity=null;localStorage.removeItem("futbol_device_token");renderIdentity()}
function renderIdentity(){const known=!!deviceIdentity;if($("knownPlayer"))$("knownPlayer").classList.toggle("hidden",!known);if($("newPlayer"))$("newPlayer").classList.toggle("hidden",known);if(known&&$("knownPlayerName"))$("knownPlayerName").textContent=deviceIdentity.name}
export async function loadState(){state=await api("state",{});syncClock(state.server_time);if($("sessionNotice"))$("sessionNotice").classList.add("hidden");const sel=$("playerSelect"),old=sel?.value||"";if(sel){sel.innerHTML='<option value="">Selecciona tu nombre</option>';for(const p of state.players||[]){const o=document.createElement("option");o.value=p.id;o.textContent=p.name+(p.suspended_until?" · suspendido":"");sel.appendChild(o)}sel.value=old}if(!state.match){$("noMatch")?.classList.remove("hidden");$("matchArea")?.classList.add("hidden");return state}$("noMatch")?.classList.add("hidden");$("matchArea")?.classList.remove("hidden");const m=state.match,l=state.lists||{confirmed:[],waiting:[],pending:[]};$("modeBadge").textContent=modeName(m.mode);$("matchDate").textContent=fmt(m.play_at);$("windowInfo").textContent=`Inscripción: ${fmt(m.opens_at)} → ${fmt(m.closes_at)}`;$("confirmedCount").textContent=`${l.confirmed.length}/${m.capacity}`;$("titularBadge").textContent=l.confirmed.length;$("waitingBadge").textContent=l.waiting.length;renderList("confirmedList",l.confirmed);renderList("waitingList",l.waiting);if(l.pending?.length){$("pendingBox").classList.remove("hidden");renderList("pendingList",l.pending)}else $("pendingBox").classList.add("hidden");tickCountdown();return state}
export async function join(useDevice=false){try{let payload={match_id:state.match.id};if(useDevice){payload.device_token=deviceToken}else{if(!$("playerSelect").value||!$("playerPin").value)throw new Error("Selecciona tu nombre e ingresa tu PIN.");payload.player_id=$("playerSelect").value;payload.pin=$("playerPin").value}const r=await api("register",payload);if(!useDevice&&$("rememberDevice").checked){const d=await api("link_device",{player_id:payload.player_id,pin:payload.pin,label:"Navegador personal"});deviceToken=d.device_token;localStorage.setItem("futbol_device_token",deviceToken);await refreshIdentity()}const label=r.status==="confirmed"?"TITULAR":r.status==="waiting"?"LISTA DE ESPERA":"PENDIENTE";result(useDevice?"knownResult":"actionResult",`Inscripción: ${label}. Orden servidor #${r.queue_no}. Hora ${fmtTime(r.registered_at||r.server_time)}`);await loadState()}catch(e){result(useDevice?"knownResult":"actionResult",e.message,true)}}
export async function cancel(useDevice=false){try{let payload={match_id:state.match.id};if(useDevice)payload.device_token=deviceToken;else{payload.player_id=$("playerSelect").value;payload.pin=$("playerPin").value;if(!payload.player_id||!payload.pin)throw new Error("Selecciona tu nombre e ingresa tu PIN.")}const r=await api("cancel",payload);result(useDevice?"knownResult":"actionResult",`Cupo cancelado. Hora servidor: ${fmtTime(r.server_time)}`);await loadState();document.dispatchEvent(new CustomEvent("futbol:statechanged"))}catch(e){result(useDevice?"knownResult":"actionResult",e.message,true)}}
export async function loadHistory(){const box=$("historyList");try{const h=await api("history",{limit:12});box.innerHTML=h.length?h.map(m=>`<details class="history-item"><summary>${fmt(m.play_at)} · ${modeName(m.mode)}</summary><p class="hint">Cupos: ${m.capacity} · Estado: ${m.status}</p><ol>${(m.players||[]).map(p=>`<li>${esc(p.name)} — ${p.status}</li>`).join("")}</ol></details>`).join(""):'<div class="empty">Aún no hay historial.</div>'}catch(e){box.innerHTML=`<div class="notice error">${esc(e.message)}</div>`}}