import{$,api,esc,state,currentConfirmed,deviceIdentity,deviceToken,result}from'./core.js';
let ts=null,pairs=Array.from({length:7},()=>[]),draft=[],sel=null;
const ap=()=>sessionStorage.getItem('futbol_admin_pin')||'';
export async function loadTeams(){if(!state?.match)return;ts=await api('team_state',{match_id:state.match.id});$('teamsDisabled').classList.toggle('hidden',!!ts.enabled);$('teamsArea').classList.toggle('hidden',!ts.enabled);if(!ts.enabled)return;official();const ok=currentConfirmed().length===14&&(ap()||(ts.proposals_enabled&&deviceIdentity&&currentConfirmed().some(x=>x.player_id===deviceIdentity.player_id)));$('teamBuilder').classList.toggle('hidden',!ok);if(ok&&pairs.flat().length===0)render()}
function official(){const o=ts.official;if(!o){$('officialTeams').classList.add('hidden');return}$('officialTeams').classList.remove('hidden');const n=Object.fromEntries(currentConfirmed().map(x=>[x.player_id,x.name])),team=t=>(o.assignments||[]).filter(x=>x.team===t).map(x=>`<div class="player-chip">${esc(n[x.player_id]||'Jugador')}</div>`).join('');$('officialTeams').innerHTML=`<div class="official-title"><h3>Equipos oficiales</h3><span class="badge">${o.status==='published'?'Publicados':'Revisar'}</span></div><div class="grid-lists"><div class="team-card team-a"><h3>Equipo A</h3>${team('A')}</div><div class="team-card team-b"><h3>Equipo B</h3>${team('B')}</div></div>`;if(o.status==='needs_review'){$('teamsReview').classList.remove('hidden');$('teamsReview').textContent='⚠️ Cambió la lista de titulares. Revisa los equipos.'}else $('teamsReview').classList.add('hidden')}
function chip(p){return`<span class="player-chip${sel===p.player_id?' selected':''}" draggable="true" data-player="${p.player_id}">${esc(p.name)}</span>`}
function render(){const c=currentConfirmed(),used=new Set(pairs.flat());$('playerPool').innerHTML=c.filter(p=>!used.has(p.player_id)).map(chip).join('');$('pairGrid').innerHTML=pairs.map((a,i)=>`<div class="pair-slot" data-pair="${i}"><strong>Pareja ${i+1}</strong><div class="pair-players">${a.map(id=>chip(c.find(x=>x.player_id===id))).join('')}</div></div>`).join('');wire();$('distributeBtn').disabled=!pairs.every(a=>a.length===2)}
function move(id,i){pairs=pairs.map(a=>a.filter(x=>x!==id));if(pairs[i].length<2)pairs[i].push(id);sel=null;draft=[];$('draftTeams').classList.add('hidden');$('teamActions').classList.add('hidden');render()}
function wire(){document.querySelectorAll('.player-chip[draggable=true]').forEach(e=>{e.ondragstart=x=>x.dataTransfer.setData('text/plain',e.dataset.player);e.onclick=()=>{sel=sel===e.dataset.player?null:e.dataset.player;render()}});document.querySelectorAll('.pair-slot').forEach(e=>{e.ondragover=x=>x.preventDefault();e.ondrop=x=>{x.preventDefault();move(x.dataTransfer.getData('text/plain'),+e.dataset.pair)};e.onclick=x=>{if(!x.target.closest('.player-chip')&&sel)move(sel,+e.dataset.pair)}})}
export function resetPairs(){pairs=Array.from({length:7},()=>[]);draft=[];render();$('draftTeams').classList.add('hidden');$('teamActions').classList.add('hidden')}
export function distributePairs(){if(!pairs.every(a=>a.length===2))return;draft=[];for(const p of pairs){const f=Math.random()<.5;draft.push({player_id:p[f?0:1],team:'A'},{player_id:p[f?1:0],team:'B'})}const n=Object.fromEntries(currentConfirmed().map(x=>[x.player_id,x.name])),out=t=>draft.filter(x=>x.team===t).map(x=>`<div class="player-chip">${esc(n[x.player_id])}</div>`).join('');$('teamADraft').innerHTML=out('A');$('teamBDraft').innerHTML=out('B');$('draftTeams').classList.remove('hidden');$('teamActions').classList.remove('hidden');$('publishOfficialBtn').classList.toggle('hidden',!ap());$('submitProposalBtn').classList.toggle('hidden',!(ts.proposals_enabled&&deviceIdentity))}
export async function saveTeam(k){try{if(k==='official')await api('admin_save_team_plan',{pin:ap(),match_id:state.match.id,pairings:pairs,assignments:draft,publish:true});else await api('player_save_team_proposal',{device_token:deviceToken,match_id:state.match.id,pairings:pairs,assignments:draft});result('teamMessage',k==='official'?'Equipos publicados.':'Propuesta enviada.');await loadTeams()}catch(e){result('teamMessage',e.message,true)}}